-- MySQL Script generated by MySQL Workbench
-- Thu Oct 28 11:36:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant` DEFAULT CHARACTER SET utf8 ;
USE `restaurant` ;

-- -----------------------------------------------------
-- Table `restaurant`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurant`.`categories` ;

CREATE TABLE IF NOT EXISTS `restaurant`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `category_idx` (`name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `restaurant`.`category_formulas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurant`.`category_formulas` ;

CREATE TABLE IF NOT EXISTS `restaurant`.`category_formulas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `f1` INT NOT NULL,
  `f2` INT NOT NULL,
  `f3` INT NULL DEFAULT NULL,
  `f4` INT NULL DEFAULT NULL,
  `f5` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `restaurant`.`formulas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurant`.`formulas` ;

CREATE TABLE IF NOT EXISTS `restaurant`.`formulas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `formula` INT NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `category_formula_key_idx` (`formula` ASC) VISIBLE,
  CONSTRAINT `category_formula_key`
    FOREIGN KEY (`formula`)
    REFERENCES `restaurant`.`category_formulas` (`id`));


-- -----------------------------------------------------
-- Table `restaurant`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurant`.`items` ;

CREATE TABLE IF NOT EXISTS `restaurant`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `description` MEDIUMTEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `category_id_key`
    FOREIGN KEY (`category_id`)
    REFERENCES `restaurant`.`categories` (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;